//
//  ChatModel.swift
//  Kakako-Clone
//
//  Created by 강윤서 on 2022/11/04.
//

import UIKit

struct ChatModel {
    var userName: String
    var profileImage: UIImage?
    var recentMessage: String
    var time: String
}

var chatModelList: [ChatModel] = [
    ChatModel(userName: "안솝트",
              profileImage: ImageLiterals.FriendTab.profileImage1,
              recentMessage: "언제 볼건데??",
              time: "오후 9:41"),
    ChatModel(userName: "김솝트",
              profileImage: ImageLiterals.FriendTab.profileImage2,
              recentMessage: "언제 볼건데??",
              time: "오후 9:24"),
    ChatModel(userName: "최솝트",
              profileImage: ImageLiterals.FriendTab.profileImage3,
              recentMessage: "언제 볼건데??",
              time: "오전 5:41"),
    ChatModel(userName: "강솝트",
              profileImage: ImageLiterals.FriendTab.profileImage4,
              recentMessage: "언제 볼건데??",
              time: "오후 10:00"),
    ChatModel(userName: "정솝트",
              profileImage: ImageLiterals.FriendTab.profileImage5,
              recentMessage: "언제 볼건데??",
              time: "오후 8:20"),
    ChatModel(userName: "이솝트",
              profileImage: ImageLiterals.FriendTab.profileImage6,
              recentMessage: "언제 볼건데??",
              time: "오전 7:41"),
    ChatModel(userName: "김솝트",
              profileImage: ImageLiterals.FriendTab.profileImage7,
              recentMessage: "언제 볼건데??",
              time: "오후 9:41"),
    ChatModel(userName: "안솝트",
              profileImage: ImageLiterals.FriendTab.profileImage8,
              recentMessage: "언제 볼건데??",
              time: "오후 3:41"),
    ChatModel(userName: "노솝트",
              profileImage: ImageLiterals.FriendTab.profileImage9,
              recentMessage: "언제 볼건데??",
              time: "오후 6:41"),
    ChatModel(userName: "박솝트",
              profileImage: ImageLiterals.FriendTab.profileImage1,
              recentMessage: "언제 볼건데??",
              time: "오후 2:41"),
    ChatModel(userName: "류솝트",
              profileImage: ImageLiterals.FriendTab.profileImage2,
              recentMessage: "언제 볼건데??",
              time: "오후 9:41"),
    ChatModel(userName: "안솝트",
              profileImage: ImageLiterals.FriendTab.profileImage1,
              recentMessage: "언제 볼건데??",
              time: "오후 9:41"),
    ChatModel(userName: "김솝트",
              profileImage: ImageLiterals.FriendTab.profileImage2,
              recentMessage: "언제 볼건데??",
              time: "오후 9:24"),
    ChatModel(userName: "최솝트",
              profileImage: ImageLiterals.FriendTab.profileImage3,
              recentMessage: "언제 볼건데??",
              time: "오전 5:41"),
    ChatModel(userName: "강솝트",
              profileImage: ImageLiterals.FriendTab.profileImage4,
              recentMessage: "언제 볼건데??",
              time: "오후 10:00"),
    ChatModel(userName: "정솝트",
              profileImage: ImageLiterals.FriendTab.profileImage5,
              recentMessage: "언제 볼건데??",
              time: "오후 8:20"),
    ChatModel(userName: "이솝트",
              profileImage: ImageLiterals.FriendTab.profileImage6,
              recentMessage: "언제 볼건데??",
              time: "오전 7:41"),
    ChatModel(userName: "김솝트",
              profileImage: ImageLiterals.FriendTab.profileImage7,
              recentMessage: "언제 볼건데??",
              time: "오후 9:41"),
    ChatModel(userName: "안솝트",
              profileImage: ImageLiterals.FriendTab.profileImage8,
              recentMessage: "언제 볼건데??",
              time: "오후 3:41"),
    ChatModel(userName: "노솝트",
              profileImage: ImageLiterals.FriendTab.profileImage9,
              recentMessage: "언제 볼건데??",
              time: "오후 6:41"),
    ChatModel(userName: "박솝트",
              profileImage: ImageLiterals.FriendTab.profileImage1,
              recentMessage: "언제 볼건데??",
              time: "오후 2:41"),
    ChatModel(userName: "류솝트",
              profileImage: ImageLiterals.FriendTab.profileImage2,
              recentMessage: "언제 볼건데??",
              time: "오후 9:41")
]
